apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node-D
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-node
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node
        image: k8s.gcr.io/echoserver:1.10
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-node
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: hello-node
  ports:
  - port: 8080
    targetPort: 8080
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-node
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: hellonode.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-node
            port:
              number: 8080


